### ISSUE TITLE
Texture conflict on ElvUI when PasteNG is installed

### ISSUE THREAD

**Issue by KayopsGaming** [GurliGebis/WoWAddon-PasteNG#1]
Hi there,

Paste NG changes a texture from ElvUI when enabled.

Addons running:
- ElvUI 13.07
- Paste NG 10.0.2-20221129_1

How to reproduce:
On ElvUI, in the Buffs and Debuffs, Buffs section enable the status bar
![image](https://user-images.githubusercontent.com/73057882/204921483-eb1e19fe-ff80-41d3-a63e-5aa3fc54f26a.png)

The bar should be present in your buffs, with the selected color in the settings
![image](https://user-images.githubusercontent.com/73057882/204921603-dbb51127-0fe4-4d7d-85b3-efd9863fd4c6.png)

Then install/enable Paste NG, the bar no longer uses the color setup in the ElvUI settings
![image](https://user-images.githubusercontent.com/73057882/204921754-bd1e5e96-6e21-429e-866b-e22fa349e3d0.png)

What should be expected:
Paste NG **should not influence** colors/textures on other addons.

**Comment by GurliGebis** [comment]
@KayopsGaming I know it has been quiet a while, but I just released a new version that is a complete rewrite.
Can you please give it a try, and reopen the ticket if the issue is still there?
It is version `11.0.2-20240920-1`
