### ISSUE TITLE
Does not load in current version

### ISSUE THREAD

**Issue by dalefrancis88** [GurliGebis/WoWAddon-PasteNG#10]
Installed via curseforge and yes it's enabled, yes i've reloaded the ui, i've uninstalled/re-installed, no i don't have the other paste addon added.

The icon does not show near the mini-map and none of the follwing commands work

/paste
/paste show
/pasteng

![image](https://github.com/user-attachments/assets/c50972b8-9821-4528-9172-d76577b726e9)

FYI this version loads

![image](https://github.com/user-attachments/assets/b9cc800d-eeda-43cd-a33d-5fadf6f0bf41)

**Comment by GurliGebis** [comment]
That's strange - are you sure the addon is loaded? (Only reason I can come up with to why it doesn't register the slash commands).

If you run the following command in the chatbox, what result does it give you? `/run print(C_AddOns.IsAddOnLoaded("Paste"))`

**Comment by river245542** [comment]
I'm not the original author, but I am having a similar issue. I ran that command in the chatbox and it says "true true'. I click the Paste button next to my minimap and it only opens with this 
![image](https://github.com/user-attachments/assets/8c842ee8-25d8-4c98-9d8b-2e330ad549b5)
and I have the same issues if I use commands 
/paste
/paste show
/pasteng
and it just shows /help for all of them.

**Comment by GurliGebis** [comment]
@river245542 Just to be sure - can you please attach the content of the `_retail_\Interface\addons\Paste\Paste.toc` file here - just to be 100% sure that everything is like it should be with the files?

**Comment by river245542** [comment]
Hello, I couldn't attach the file so I just copied the stuff in it.
## Interface: 70100
## Title: Paste
## Description: Enables multi-line/unlimited-length pasting of text or commands into WoW
## Notes: Enables multi-line/unlimited-length pasting of text or commands into WoW
## Author: oscarucb
## Credits: 
## Version: 1.4.10
## X-Build: 55
## X-ReleaseDate: 2016-11-15T23:51:08Z
## X-Revision: $Revision: 55 $
## SavedVariables: PasteDB 
## SavedVariablesPerCharacter: 
## X-Embeds: Ace3, LibDataBroker-1.1, LibDBIcon-1.0, LibStrataFix
## OptionalDeps: Ace3, LibDataBroker-1.1, LibDBIcon-1.0
## LoadManagers: AddonLoader
## X-LoadOn-Always: delayed
## X-LoadOn-Slash: /paste
## X-Curse-Packaged-Version: 1.4.10
## X-Curse-Project-Name: Paste
## X-Curse-Project-ID: paste
## X-Curse-Repository-ID: wow/paste/mainline

embeds.xml

locale.lua

core.lua

**Comment by GurliGebis** [comment]
That is the old paste addon (release date back in 2016).
Please delete the `Paste` folder from your addons folder, make sure whatever you use to install addons doesn't have `Paste` listed - if it does, uninstall it.
Then search for `PasteNG` (remember the NG suffix), and install that.
@dalefrancis88 can you please check as well, if what you are seeing is the same?

**Comment by GurliGebis** [comment]
If you update to the version `11.0.2-20240920-1` I have released today (it is a complete rewrite with more features), it should warn if the old version is still installed.

If the issue is still there after updating to this version please reopen the ticket.
