### ISSUE TITLE
Unable to uncheck minimap option

### ISSUE THREAD

**Issue by Gaviin1242** [GurliGebis/WoWAddon-PasteNG#13]
Using latest version (just downloaded today), I'm unable to hide the minimap button.  When I go into options, click on "Enable Minimap Icon" doesn't uncheck it.

**Comment by GurliGebis** [comment]
Thanks, I'll get it fixed tomorrow 🙂

**Comment by jabrabec** [comment]
I am in the same boat where the UI option could not be unchecked, so I thought I'd just edit the LUA manually to make it go away in the meantime, but it appears it's set to `false` there already:
`["enableMinimapIcon"] = false`
Hope this helps!

**Comment by Jdaddy0007** [comment]
> Thanks, I'll get it fixed tomorrow 🙂
Thank you! Love your addon!

**Comment by GurliGebis** [comment]
I have just pushed `11.0.2-20240921-1` which fixes the problem.
Please test and reopen if the issue is still there.
