### ISSUE TITLE
Can't hide minimap icon in new build

### ISSUE THREAD

**Issue by raptormama** [GurliGebis/WoWAddon-PasteNG#15]
When clicking the option to hide the minimap icon in the new build of the adodn, nothing happens.

Doesn't seem to throw a Lua error, though.

**Comment by GurliGebis** [comment]
I pushed a fix for this 15 minutes ago 😃
Please try the latest version from today, and reopen if the issue persists.

**Comment by raptormama** [comment]
Huh! Looks like you published just as I reported. It does appear to work correctly now.

Thank you!

**Comment by GurliGebis** [comment]
You're welcome 🙂
