### ISSUE TITLE
Addon no longer showing via data broker (e.g., Bazooka)

### ISSUE THREAD

**Issue by Gaviin1242** [GurliGebis/WoWAddon-PasteNG#16]
With the change to allow disabling the minimap icon, PasteNG no longer shows up via data broker such as Bazooka.  Doesn't even show in the list.  It did in the previous versions, including the one where the minimap icon couldn't be disabled.

**Comment by GurliGebis** [comment]
Okay, so just to be sure - it works with `11.0.2-20240920-1` but not `11.0.2-20240921-1` ?

If that is the case, could you try and revert this line back and see if that makes a difference for you?
https://github.com/GurliGebis/WoWAddon-PasteNG/commit/185ebd17e57c74395627b96db28664bd3740cfbd#diff-0b751b59c9d50ad473976ffed2a401d19dbf2c9fe2d688bc7597b7a95df96cefR75

**Comment by Gaviin1242** [comment]
Hmm, I tried reverting to a couple of the most recent versions, and seems the last version where data broker works is 11.0.2-20240912-1.  I could have sworn it was working with 920-1, but it's not now.

**Comment by GurliGebis** [comment]
Okay, that makes sense 🙂
I'll see what needs to be changed for it to work with brokers.

**Comment by GurliGebis** [comment]
I just tried installing Bazooka myself.
It appears just fine in the top bar:

![billede](https://github.com/user-attachments/assets/e0cf2d07-fff1-4ffb-82d2-512d4567aeb4)

I'm not sure what fails for you, it but seems to be working.
@tflo in #18 also has it working in Bazooka.

Could you try with only Bazooka and PasteNG loaded? (Just in case something else is causing issues)

**Comment by tflo** [comment]
Referring to my comment in #18: Tried it again with Bazooka _and all addons except Bazooka and PasteNG unloaded_: Still works fine.

Installed Chocolate Bar (a broker addon similar to Bazooka) and tried it with that: Works also.

**Comment by Gaviin1242** [comment]
Just tested with the latest version, and still having an issue.  But it's strange.

When I load the game, PasteNG is nowhere to be seen in the Bazooka bar or config.  But if I go into the PasteNG options and re-enable the minimap icon, it suddenly shows up in Bazooka (bar and config).  However, once I reload UI or re-log into the game, back to square one.

Now, if I leave the minimap icon option enabled, then it'll stay in Bazooka and persist between sessions.  But... obviously that somewhat defeats the purpose of using the broker addon to centralize addon management vs. using minimap icons.  :)

The above description applies to running with just Bazooka and PasteNG enabled, as well as to running all the addons I usually run. I.e., doesn't seem to be caused by a clash with other addons.

**Comment by GurliGebis** [comment]
Okay, I think I know what is happening.
Let me see if I got it right 🙂

You want the minimap icon disabled, but it still visible in a broker, correct?

**Comment by tflo** [comment]
> I can then disable the minimap icon option, and it stays showing in Bazooka as one would expect. However, once I reload UI or re-log into the game, back to square one

Oh, I can confirm this. _After a reload_ (and with the minimap icon disabled), the LDB icon disappears. Sorry,  I didn't properly test this [before](https://github.com/GurliGebis/WoWAddon-PasteNG/issues/16#issuecomment-2366954791); I just disabled/enabled the minimap icon _without reload_, but this doesn't expose the bug.

(And before and after the test, I had _both_ disabled, because the hotkey is back ;)

**Comment by GurliGebis** [comment]
I'm 99% sure I have figured out what changes I need to make.
I'll test them tonight, and if it works as expected, I'll push a new release 😊

**Comment by b-morgan** [comment]
For me, the Titan Panel option disappeared with the 20240922-1 release. I toggled the Enable Minimap Icon (on) and the Titan Panel option appeared. I toggled the Enable Minimap Icon (off) and the Titan Panel option remained.

**Comment by LordDeimos666** [comment]
Can confirm, also elvui can't see the databroker.

**Comment by GurliGebis** [comment]
I think the code changes I have will solve the issue.
Should get time to test it tomorrow 🙂

**Comment by Gaviin1242** [comment]
Correct. Thanks again for working on this!




On Sunday, September 22, 2024, 11:09 PM, GurliGebis ***@***.***> wrote:




Okay, I think I know what is happening.
Let me see if I got it right 🙂

You want the minimap icon disabled, but it still visible in a broker, correct?

**Comment by b-morgan** [comment]
The minimap icon visible and the broker visible should be independent. Either let the broker visibility be controlled by the broker (my preference) or make an independent option for it.

**Comment by GurliGebis** [comment]
I know, that is what I have done in my local development version, just need to test it tomorrow before I release it 😃

**Comment by GurliGebis** [comment]
I have just pushed `11.0.2-20240924-1` which fixes it.
It decouples the visibility of the minimap icon with the creation of the data broker object.
