### ISSUE TITLE
Keybind?

### ISSUE THREAD

**Issue by tflo** [GurliGebis/WoWAddon-PasteNG#18]
It seems you have removed the Bindings.xml with your rewrite(?)

Please consider re-adding it, my keybind to call Paste is in my muscle memory 😉

**Comment by GurliGebis** [comment]
Hey,

It is already in my next batch of changes, so coming really soon 🙂
Just got one more thing to figure out first (why databrokers don't see it)

**Comment by tflo** [comment]
> why databrokers don't see it)

No problem here (using [Bazooka](https://www.curseforge.com/wow/addons/bazooka)):

<img width="273" alt="image" src="https://github.com/user-attachments/assets/17b4f2e7-79d8-4678-aeb4-b2fcf6acd53d">

**Comment by GurliGebis** [comment]
@tflo interresting - I haven't had time to test it myself with a broker.
Could I ask you to help look into what is going wrong in #16 ?

I'll be pushing a new version shortly with keybinding support 🙂

**Comment by GurliGebis** [comment]
I just pushed `11.0.2-20240922-1` a few seconds ago with keybinding support - should hit the mirrors within an hour or two.

**Comment by tflo** [comment]
Keybind works fine now, thanks for the quick fix!

**Comment by GurliGebis** [comment]
You're very welcome 🙂
