### ISSUE TITLE
Minimap Icon Disappeared

### ISSUE THREAD

**Issue by panseit** [GurliGebis/WoWAddon-PasteNG#21]
Since the latest build (11.0.2-20240922-1) the minimap icon completely disappeared and the command to bring it back doesn't do anything :/

**Comment by GurliGebis** [comment]
What happens if you type /paste ?

**Comment by GurliGebis** [comment]
I have just pushed `11.0.2-20240924-1` - could you give that a try?
It reworks several parts of the minimap icon logic.

If it still fails, please reopen, and paste a screenshot of what the settings dialog for the addon shows.
