### ISSUE TITLE
Double "Ok"

### ISSUE THREAD

**Issue by Machou** [GurliGebis/WoWAddon-PasteNG#25]
Hello!

I've seen the new improvement for pressing “Ok” (`c2a61eb9f1573522a19a64d003d78f4de96979c9`) when saving a Paste, but can you add for the second window? That way you press “Ok” twice :)

Thanks a lot!

**Comment by GurliGebis** [comment]
Are you talking about the `This will overwrite an existing saved paste, are you sure?` dialog?

**Comment by Machou** [comment]
> Are you talking about the `This will overwrite an existing saved paste, are you sure?` dialog?

Yes ^^

**Comment by GurliGebis** [comment]
I can do that 🙂
Might be a few days before I get time to fix it though

**Comment by GurliGebis** [comment]
There doesn't seem to be a way to catch the Enter keypress without a textbox there.
So while I would like to add this, it doesn't seem like it is possible. (And adding a textbox, just to allow capture of enter doesn't make sense).

**Comment by GurliGebis** [comment]
I need to read the documentation better - new release incoming 🙂

**Comment by GurliGebis** [comment]
I have released `11.0.2-20241015-1` which implements this
