### ISSUE TITLE
Updated embedded libraries

### ISSUE THREAD

**Issue by filliph** [GurliGebis/WoWAddon-PasteNG#4]
When compared to https://www.tukui.org/addons.php?id=186 all of the embedded libraries are vastly out of date. F.ex. AceGUI is from 2013 in PasteNG compared to 2020 in CopyPasta2.

I would recommend downloading new versions of all embedded libraries to ensure there are no conflicts or issues when running this alongside newer addons.

**Comment by GurliGebis** [comment]
I have released a new version with the embedded libraries updated.
