### ISSUE TITLE
Save the "Pastes".

### ISSUE THREAD

**Issue by Machou** [GurliGebis/WoWAddon-PasteNG#5]
Hello,

A feature that many players are waiting for is a kind of note, could you implement it for us? It's a great way to keep track of the progress of an achievement for example, so you don't have to go back and get the content, etc.

Thanks for taking over!

**Comment by GurliGebis** [comment]
I'll see what I can do, but I cannot promise anything.

**Comment by Machou** [comment]
Good thanks

**Comment by tflo** [comment]
Hi @Machou , I just stumbled across your post while browsing the issues here.

It is possible that I completely misread your suggestion…

> A feature that many players are waiting for is a kind of note […] to keep track of the progress of an achievement for example

…, but it seems to me that you are trying to use PasteNG as sort of a notepad.  There is already an excellent and actively developed in-game notepad addon: [TinyPad](https://www.curseforge.com/wow/addons/tinypad) really leaves nothing to be desired, IMHO. 

You can even paste links into it, or you can use it to run scripts _without the need to paste the script to the chat at all_ (for example such things like `C_QuestLog.IsQuestFlaggedCompleted(questID)`.)

I’m not affiliated with the developer of TinyPad, just a user. Hope this helps!

**Comment by Machou** [comment]
I know TinyPad, but I prefer Paste, much simpler, and the text is better arranged, I don't know why it's just a feeling.
But I made a note on Excel now I'm used to work with it :)

**Comment by GurliGebis** [comment]
Good news, I am close to having finished a complete rewrite of the PasteNG addon, which has save/load functionality 😃

**Comment by Machou** [comment]
> Good news, I am close to having finished a complete rewrite of the PasteNG addon, which has save/load functionality 😃

Glad to hear it! Can't wait to see the result!

**Comment by GurliGebis** [comment]
I just pushed `11.0.2-20240920-1` a few minutes ago 🙂

Check this out:

![The main PasteNG window](https://raw.githubusercontent.com/GurliGebis/WoWAddon-PasteNG/master/Images/main-window.webp)

**Comment by Machou** [comment]
@GurliGebis Coool !

When i use `/pasteng minimap` or here:

![Sans titre](https://github.com/user-attachments/assets/8af2764e-7c27-44aa-94bd-e47375b8b432)

Didn't work.

**Comment by Machou** [comment]
@GurliGebis

en_US : error :

**Please enter the of your paste:**
https://legacy.curseforge.com/wow/addons/pasteng/localization/languages/93/phrases#460110

fr_FR is done. You can update =)

**Comment by GurliGebis** [comment]
Thanks, I'll fix both issues tomorrow and make a new release.

**Comment by GurliGebis** [comment]
I have just pushed `11.0.2-20240921-1` which fixes the problems.
Please test and reopen if the issue is still there.
@Machou thanks for providing the frFR translation - please double check it, since I have renamed the string in the english version.

**Comment by Machou** [comment]
> I have just pushed `11.0.2-20240921-1` which fixes the problems. Please test and reopen if the issue is still there. @Machou thanks for providing the frFR translation - please double check it, since I have renamed the string in the english version.

I have update fr_FR too !

And all is worked perfect !

Options that could be cool:

- Always centre the note
- Be able to lock it in a fixed position
- Keep the same window size when disconnecting / reconnecting

**Comment by GurliGebis** [comment]
Keeping the position is default, I'll add an option to save the size as well, along with an option to save position (both enabled by default).

I'll see if I can lock the window on screen, it depends on if Ace3 supports it for frames.

**Comment by Machou** [comment]
> Keeping the position is default, I'll add an option to save the size as well, along with an option to save position (both enabled by default).
> 
> I'll see if I can lock the window on screen, it depends on if Ace3 supports it for frames.

with Ace3 yes you can like:

```lua
local frame = AceGUI:Create("Frame")
frame:SetTitle("Frame Example")
frame:SetStatusText("Status text")
frame:SetCallback("OnClose", function(widget) AceGUI:Release(widget) end)

-- Lock the frame
frame.frame:EnableMouse(false)
```

**Comment by GurliGebis** [comment]
I see - however, resizing if it is locked on screen might prove a bad idea (since the top and left is locked).

Any ideas on how to implement that, so it stays centered, even when resized?

**Comment by GurliGebis** [comment]
Also, it doesn't seem like it wants to lock the dialog so it cannot be moved.

So, I think remembering positions between logins and warning about overwriting should be easy enough.

**Comment by GurliGebis** [comment]
I managed to get some of it done - I will release a new version later tonight.

@Machou I have added the following strings, if you want to translate them before I push the next release 🙂

```
L["Positions and coordinates"]
L["Reset window size and position"]
L["Resets the window size and position on screen to the default"]
L["This will overwrite an existing saved paste, are you sure?"]
L["Window size and position has been reset."]
```

**Comment by Machou** [comment]
> Any ideas on how to implement that, so it stays centered, even when resized?

Sorry, i'm not Lua developper, i'm really newb with this code :P

fr_FR is updated

**Comment by GurliGebis** [comment]
No worries - I've just pushed the new version a few seconds ago.

Here is what I have added:
* Don't hardcode Accept and Cancel.
* Persist window size across logins.
* Add config button to reset window size and position.
* Warn if a paste is about to be overwritten.

**Comment by Machou** [comment]
> No worries - I've just pushed the new version a few seconds ago.
> 
> Here is what I have added:
> 
>     * Don't hardcode Accept and Cancel.
> 
>     * Persist window size across logins.
> 
>     * Add config button to reset window size and position.
> 
>     * Warn if a paste is about to be overwritten.

The main work has been done!

Improvements will follow, if the addon becomes an ‘essential’!

Thank you for all your hard work.

I think we can close the issue!

**Comment by GurliGebis** [comment]
You're welcome, and if you get any ideas, just let me know 🙂
After the rewrite, maintaining and adding new features has become much easier
