### ISSUE TITLE
Adding icon to addonlist

### ISSUE THREAD

**Issue by Zakoom** [GurliGebis/WoWAddon-PasteNG#8]
adding the line
## #IconTexture: 134944

to add a icon in the addonlist
![example](https://github.com/user-attachments/assets/4e2f845b-4800-42a4-93b7-0f38c5f1cb6b)

**Comment by GurliGebis** [comment]
Thanks, I'll fix that today or tomorrow 👍

**Comment by GurliGebis** [comment]
I have released `11.0.2-20240831-1` with the change 🙂
